CRITICAL - 2022-06-11 00:17:07 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-11 00:17:07 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-11 00:17:08 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-11 00:17:08 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
