ERROR - 2022-06-01 06:58:37 --> ErrorException: pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;user_pk&quot;
DETAIL:  Key (id)=(1) already exists. in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #117, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(48): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 06:58:37 --> pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;user_pk&quot;
DETAIL:  Key (id)=(1) already exists.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #117, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(48): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 06:58:38 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\202210019\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-01 06:59:21 --> ErrorException: pg_query(): Query failed: ERROR:  null value in column &quot;id&quot; of relation &quot;user&quot; violates not-null constraint
DETAIL:  Failing row contains (null, hakim, b6be14bceb32e2083e4162e4ccce2cd5, null, 2022-06-01 18:59:20.903872, null, 2022-06-01 18:59:20.903872). in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #117, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(48): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 06:59:21 --> pg_query(): Query failed: ERROR:  null value in column &quot;id&quot; of relation &quot;user&quot; violates not-null constraint
DETAIL:  Failing row contains (null, hakim, b6be14bceb32e2083e4162e4ccce2cd5, null, 2022-06-01 18:59:20.903872, null, 2022-06-01 18:59:20.903872).
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #117, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(48): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 06:59:21 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\202210019\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-01 06:59:32 --> ErrorException: pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;user_pk&quot;
DETAIL:  Key (id)=(1) already exists. in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #117, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(48): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 06:59:32 --> pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;user_pk&quot;
DETAIL:  Key (id)=(1) already exists.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #117, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(48): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 06:59:32 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\202210019\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-01 07:04:15 --> ErrorException: pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;user_pk&quot;
DETAIL:  Key (id)=(1) already exists. in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #117, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(48): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:04:25 --> pg_query(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;user_pk&quot;
DETAIL:  Key (id)=(1) already exists.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #117, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(48): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-06-01 07:37:27 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression. in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #125, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:37:27 --> pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #125, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:37:29 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\202210019\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-01 07:39:33 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression. in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #125, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:39:33 --> pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #125, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:39:33 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\202210019\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-01 07:42:34 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression. in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #126, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:42:34 --> pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #126, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:42:34 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\202210019\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-01 07:56:13 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression. in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #125, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:56:13 --> pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #125, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-06-01 07:57:01 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression. in C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #125, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 07:57:01 --> pg_query(): Query failed: ERROR:  column &quot;created_at&quot; is of type uuid but expression is of type integer
LINE 1: ...hakim', 'b6be14bceb32e2083e4162e4ccce2cd5', '06/01/2022', 1)
                                                                     ^
HINT:  You will need to rewrite or cast the expression.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 135, Array)
#1 C:\xampp\htdocs\202210019\system\Database\Postgre\Connection.php(135): pg_query(Resource id #125, 'INSERT INTO "us...')
#2 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "us...')
#3 C:\xampp\htdocs\202210019\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "us...')
#4 C:\xampp\htdocs\202210019\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO "us...', Array, false)
#5 C:\xampp\htdocs\202210019\app\Controllers\User.php(61): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#7 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-06-01 08:56:27 --> Undefined variable: query
#0 C:\xampp\htdocs\202210019\app\Controllers\User.php(16): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 16, Array)
#1 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->get_user_list()
#2 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-01 21:56:58 --> Undefined variable: session
#0 C:\xampp\htdocs\202210019\app\Controllers\User.php(57): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 57, Array)
#1 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->add()
#2 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-01 22:56:32 --> Undefined variable: query
#0 C:\xampp\htdocs\202210019\app\Controllers\User.php(35): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 35, Array)
#1 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->get_user('2')
#2 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-01 22:56:49 --> Undefined variable: query
#0 C:\xampp\htdocs\202210019\app\Controllers\User.php(35): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 35, Array)
#1 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->get_user('2')
#2 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-01 22:58:31 --> Undefined variable: query
#0 C:\xampp\htdocs\202210019\app\Controllers\User.php(35): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 35, Array)
#1 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->get_user('2')
#2 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-01 23:00:45 --> Undefined variable: result
#0 C:\xampp\htdocs\202210019\app\Controllers\User.php(45): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 45, Array)
#1 C:\xampp\htdocs\202210019\system\CodeIgniter.php(832): App\Controllers\User->get_user('2')
#2 C:\xampp\htdocs\202210019\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 C:\xampp\htdocs\202210019\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\202210019\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-06-01 23:00:49 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\202210019\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\202210019\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\202210019\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
